<a href="https://colab.research.google.com/github/palVikram/Machine-Learning-using-Python/blob/master/Numpy_implementation_Data_science_important_concepts" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### Steps to create dropout
import numpy as np

# Example usage:
X = np.random.rand(5, 5)
X

array([[0.14635991, 0.01133066, 0.66539399, 0.74127252, 0.62321183],
       [0.07453104, 0.70923138, 0.72681232, 0.4364586 , 0.44353092],
       [0.82410157, 0.11618204, 0.92170095, 0.48524298, 0.87681611],
       [0.01759614, 0.21426306, 0.10340425, 0.16864473, 0.91107617],
       [0.76861997, 0.37522717, 0.672222  , 0.27148641, 0.3015718 ]])

In [ ]:
dropout_rate=0.5
retain_prob=1-dropout_rate

In [ ]:
 np.random.binomial(1, retain_prob, size=X.shape)

array([[0, 0, 0, 1, 1],
       [1, 1, 1, 0, 1],
       [1, 0, 1, 0, 1],
       [0, 0, 1, 1, 0],
       [1, 0, 0, 0, 0]])

In [ ]:
mask=np.random.binomial(1, retain_prob, size=X.shape)/retain_prob
mask

array([[2., 2., 0., 2., 2.],
       [2., 2., 2., 0., 0.],
       [0., 2., 2., 2., 2.],
       [2., 2., 2., 2., 0.],
       [2., 0., 0., 2., 0.]])

In [ ]:
X*mask

array([[0.        , 0.02266133, 0.        , 0.        , 0.        ],
       [0.        , 1.41846276, 1.45362464, 0.        , 0.88706183],
       [1.64820314, 0.        , 0.        , 0.        , 0.        ],
       [0.03519229, 0.        , 0.        , 0.33728945, 1.82215235],
       [0.        , 0.75045433, 1.34444399, 0.        , 0.60314359]])

In [ ]:
import numpy as np

X=np.random.rand(5,5)

gamma=np.ones(X.shape[1])
beta=np.zeros(X.shape[1])

gamma, beta

(array([1., 1., 1., 1., 1.]), array([0., 0., 0., 0., 0.]))

In [ ]:
### x=(X-mean)/sqrt(variance+e)
### Gamma: No scaling
### Beta: No Shifting
mean=np.mean(X, axis=0)
variance=np.var(X, axis=0)

e=1e-8
normalization=(X-mean)/np.sqrt(variance+e)

gamma=np.ones(X.shape[1])
beta=np.zeros(X.shape[1])

print(normalization)
normalization*gamma+beta

[[-1.14602588  0.1007797  -1.68253673  0.85579513  1.73328787]
 [ 1.30300157  0.4509045   1.00244688 -1.16865403  0.01030518]
 [ 1.01623838 -1.12185311  0.22866793  0.61347388 -0.7603822 ]
 [-0.22064589 -1.01211007 -0.48491815 -1.26393374 -1.17500626]
 [-0.95256818  1.58227898  0.93634008  0.96331876  0.19179541]]


array([[-1.14602588,  0.1007797 , -1.68253673,  0.85579513,  1.73328787],
       [ 1.30300157,  0.4509045 ,  1.00244688, -1.16865403,  0.01030518],
       [ 1.01623838, -1.12185311,  0.22866793,  0.61347388, -0.7603822 ],
       [-0.22064589, -1.01211007, -0.48491815, -1.26393374, -1.17500626],
       [-0.95256818,  1.58227898,  0.93634008,  0.96331876,  0.19179541]])

In [ ]:
#The Adam optimizer combines the advantages of two other extensions of stochastic gradient descent: \
#Adaptive Gradient Algorithm (AdaGrad) and Root Mean Square Propagation (RMSProp).

"""
First Moment Estimate(Mean):
mt=beta(1)*m(t-1)+(1-beta(1)).g(t)
g(t) is the gradient at time step t.

Bias Correct First Moment Estimate:
m^(t)=m(t)/(1-beta(t))
------------------------------------------
Second Moment Estimate (uncentered variance).
v(t)=beta(1)*m(t-1)+(1-beta(1)).g(t)^2

v^(t)=v(t)/(1-beta(t))

-------------------------------------
Parameter update:
theta=theta(t-1)- (alpha*m^(t)/(sqrt(v^t+epls)))

Adam adjusts the learning rate based on the first and second moments of the gradients
"""

In [ ]:
class AdamOptimizer:
  def __init__(self, lr=0.001, beta1=0.9, beta2=0.999, epsilon=1e-8):
    self.lr=lr
    self.beta1=beta1
    self.beta2=beta
    self.epsilon=epsilon
    self.m=None
    self.v=None
    self.t=0

  def update(self, params, grads):
    if self.m is None:
      self.m=np.zeros_like(params)
      self.v=np.zeros_like(params)

    self.t+=1

    self.m=self.beta1*self.m+ (1-self.beta1)*grads
    self.v=self.beta2*self.v+ (1-self.beta2)*(grads**2)

    m_hat=self.m/(1-self.beta1*self.t)
    v_hat=self.v/(1-self.beta2*self.t)

    params -=self.lr* m_hat/ (np.sqrt(v_hat)+self.epsilon)

    return params

params = np.random.rand(5, 5)
grads = np.random.rand(5, 5)
adam = AdamOptimizer()
updated_params = adam.update(params, grads)
print(updated_params)

[[0.6160768  0.29453325 0.76647752 0.95353284 0.4898694 ]
 [0.54744692 0.18264579 0.54541644 0.60484666 0.0733511 ]
 [0.68868943 0.99086443 0.20968608 0.23156483 0.70653511]
 [0.46311339 0.40777608 0.48843327 0.00536044 0.48541724]
 [0.70512852 0.42231822 0.31508844 0.07083577 0.53763574]]


In [ ]:
#Cross Entropy Loss
#Cross-entropy loss measures the performance of a classification model whose output is a probability value between 0 and 1.
#Cross-entropy loss is a commonly used loss function for classification problems. It measures the difference between two probability\
#distributions - the true labels and the predicted probabilities.

'''
y_true: True Label (one-hot encoded)
y_pred: Predicted probabilities
loss=- summation(y_true * log(y_pred))

--------------------------------
Clipping for Numerical Stability
To avoid logarithm of zero (which is undefined), the predicted probabilities are clipped:


np.clip limits the values in y_pred to be within the range [epsilon, 1 - epsilon].
This means:
Any value less than epsilon will be set to epsilon.
Any value greater than 1 - epsilon will be set to 1 - epsilon.

---------------------------------
y_pred=clip(y_pred, epls, 1-epls)


becuase log(0) is undefined, no value.
'''

In [ ]:
def cross_entrophy(y_pred, y_true):
  epsilon = 1e-15
  y_clip=np.clip(y_pred, epsilon, 1-epsilon)

  return -np.sum(y_true*np.log(y_clip))

y_pred=np.array([0.7, 0.2,0])
y_true= np.array([1,0,1])

cross_entrophy(y_pred, y_true)

34.89545133884942

In [ ]:
#Sigmoid Activation Function
#Sigmoid is a commonly used activation function in neural networks.


'''
σ(x): The sigmoid function applied to x
x: The input to the function, which can be any real number.
e: Euler's number, approximately equal to 2.71828.

σ(x)= 1/1+e−x

'''

def sigmoid(x):
  return 1/(1+np.exp(-x))


x=np.rand(5)

sigmoid_x=sigmoid(x)

print(sigmoid_x)

In [ ]:
### Linear Regression Code
def linear_regression(X, y, lr=0.01, epochs=1000):
    m, n = X.shape
    W = np.zeros(n)
    b = 0

    for epoch in range(epochs):
        y_pred = np.dot(X, W) + b
        error = y_pred - y

        W -= lr * (1/m) * np.dot(X.T, error)
        b -= lr * (1/m) * np.sum(error)

    return W, b

# Example usage:
X = np.random.rand(100, 3)
y = np.random.rand(100)
W, b = linear_regression(X, y)
print(W, b)


In [ ]:
'''
Normalization
Normalization scales the input data to have a mean of 0 and a standard deviation of 1.
'''
def normalize(X):
    mean = np.mean(X, axis=0)
    std = np.std(X, axis=0)
    return (X - mean) / std

X = np.random.rand(5, 5)
normalized_X = normalize(X)
print(normalized_X)

In [ ]:
def logistic_regression(X, y, lr=0.01, epochs=1000):
    m, n = X.shape
    W = np.zeros(n)
    b = 0

    print(m,n)
    print(W)

    for epoch in range(epochs):
        z = np.dot(X, W) + b
        y_pred = sigmoid(z)

        error = y_pred - y
        dW = (1/m) * np.dot(X.T, error)
        db = (1/m) * np.sum(error)

        W -= lr * dW
        b -= lr * db

    return W, b

def predict(X, W, b):
    z = np.dot(X, W) + b
    probabilities = sigmoid(z)
    return np.where(probabilities >= 0.5, 1, 0)

np.random.seed(0)
X = np.random.rand(100, 2)
y = np.random.randint(0, 2, 100)

W, b = logistic_regression(X, y, lr=0.1, epochs=1000)
predictions = predict(X, W, b)

print("Weights:", W.flatten())
print("Bias:", b)
print("First 10 Predictions:", predictions[:10].flatten())
print("First 10 True Labels:", y[:10])

100 2
[0. 0.]
Weights: [-0.49904328  0.81318917]
Bias: -0.13626641366176775
First 10 Predictions: [1 1 1 1 0 0 1 0 1 1]
First 10 True Labels: [0 1 0 0 1 1 1 1 1 0]


In [16]:
def softmax(x):
    """Compute softmax values for each set of scores in x."""
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / np.sum(e_x, axis=-1, keepdims=True)

def scaled_dot_product_attention(Q, K, V, mask=None):
    """Compute the scaled dot-product attention."""
    d_k = Q.shape[-1]
    scores = np.dot(Q, K.transpose(-2, -1)) / np.sqrt(d_k)

    if mask is not None:
        scores += (mask * -1e9)  # Apply mask to scores (optional)

    attention_weights = softmax(scores)
    output = np.dot(attention_weights, V)
    return output, attention_weights

def multi_head_attention(Q, K, V, num_heads):
    """Compute the multi-head attention."""
    batch_size, seq_length, d_model = Q.shape
    assert d_model % num_heads == 0, "d_model must be divisible by num_heads"
    d_head = d_model // num_heads

    # Initialize random projection matrices
    W_Q = np.random.rand(d_model, d_model)
    W_K = np.random.rand(d_model, d_model)
    W_V = np.random.rand(d_model, d_model)
    W_O = np.random.rand(d_model, d_model)

    # Project Q, K, V
    Q_proj = np.dot(Q, W_Q)
    K_proj = np.dot(K, W_K)
    V_proj = np.dot(V, W_V)

    # Split Q, K, V into multiple heads
    def split_heads(x):
        x = x.reshape(batch_size, seq_length, num_heads, d_head)
        return np.transpose(x, (0, 2, 1, 3))  # (batch_size, num_heads, seq_length, d_head)

    Q_heads = split_heads(Q_proj)
    K_heads = split_heads(K_proj)
    V_heads = split_heads(V_proj)


    # Compute attention for each head
    attention_outputs = []
    for i in range(num_heads):
        output, _ = scaled_dot_product_attention(Q_heads[:, i], K_heads[:, i], V_heads[:, i])
        attention_outputs.append(output)

    # Concatenate heads
    def concatenate_heads(x):
        x = np.transpose(x, (0, 2, 1, 3))  # (batch_size, seq_length, num_heads, d_head)
        return x.reshape(batch_size, seq_length, d_model)  # (batch_size, seq_length, d_model)

    concatenated = concatenate_heads(np.stack(attention_outputs, axis=1))

    # Final linear layer
    output = np.dot(concatenated, W_O)
    return output

# Example usage:
np.random.seed(0)
batch_size = 2
seq_length = 5
d_model = 8
num_heads = 2

# Randomly initialize Q, K, V matrices
Q = np.random.rand(batch_size, seq_length, d_model)
K = np.random.rand(batch_size, seq_length, d_model)
V = np.random.rand(batch_size, seq_length, d_model)

# Compute multi-head attention
output = multi_head_attention(Q, K, V, num_heads)
print("Multi-Head Attention Output:\n", output)


array([0.65900114, 0.24243297, 0.09856589])

In [ ]:
def sliding_window_attention(Q, K, V, window_size):
    """Compute sliding window attention."""
    batch_size, seq_length, d_model = Q.shape
    output = np.zeros_like(Q)

    for i in range(seq_length):
        # Determine the start and end of the window
        start = max(0, i - window_size)
        end = i + 1

        # Select the window of keys and values
        Q_i = Q[:, i:i+1, :]  # Shape: (batch_size, 1, d_model)
        K_window = K[:, start:end, :]  # Shape: (batch_size, window_length, d_model)
        V_window = V[:, start:end, :]  # Shape: (batch_size, window_length, d_model)

        # Compute attention scores
        scores = np.matmul(Q_i, K_window.transpose(0, 2, 1)) / np.sqrt(d_model)
        attention_weights = softmax(scores)

        # Compute output for the current position
        output[:, i:i+1, :] = np.matmul(attention_weights, V_window)

    return output

np.random.seed(0)
batch_size = 2
seq_length = 10
d_model = 8
window_size = 3

# Randomly initialize Q, K, V matrices
Q = np.random.rand(batch_size, seq_length, d_model)
K = np.random.rand(batch_size, seq_length, d_model)
V = np.random.rand(batch_size, seq_length, d_model)

# Compute sliding window attention
output = sliding_window_attention(Q, K, V, window_size)
print("Sliding Window Attention Output:\n", output)
